title: "Kacie Wielgus (Buzzard)"
description: "Speaker & Consultant"
markdown: kramdown

# If your Netlify domain is kacies.life:
url: "https://kacies.life"
baseurl: ""

permalink: pretty

collections:
  excerpts:
    output: true
    permalink: /excerpts/:name/

defaults:
  - scope:
      path: ""
    values:
      layout: default
